baseURL = "https://keishasperkins.com/"
languageCode = "en-us"
title = "Keisha S Perkins"
disqusShortname = "keishasperkins"
publishDir = "docs"


[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"